name: Java CI/CD Pipeline Minimal

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Rodar testes unitários
        run: mvn test

      - name: Compilar e empacotar
        run: mvn package -DskipTests

      - name: Upload artefato da build
        uses: actions/upload-artifact@v3
        with:
          name: java-package
          path: target/*.jar
